### ISSUE TITLE
Seed row generation

### ISSUE THREAD

**Issue by jacksonb-cs** [uark-self-assembly/TM-slat-generator#1]
The current procedure for generating and simulating the seed row is problematic.

### Current procedure
Unique, individual slats are created to assemble the entire seed row. The system is seeded only with a single macrotile, consisting of four slats.

### Issues with this approach
- Experimental approaches utilize entire DNA origamis to seed the system, so this procedure is unrealistic.
- Simulation of the assembly of the seed row takes time and must be done before the rest of the system can be simulated. This adds up over many simulations and makes debugging a system tedious.
- The counts for unique numbers of slats and domains are currently estimations because they count members that would, in reality, be replaced by a single origami.

### To-Do
- [ ] Improve the code for generating the seed in general. It was one of the first pieces of the project written, and its lack of organization shows.
- [ ] TilesetToXML() is currently not equipped to define an entire assembly as a seed. It needs to be converted to seed the system with an entire "origami".
- [ ] Analytics in TM_slat_gen.py need to be rearranged to handle the newly decoupled seed generation procedure.
- [ ] Estimations performed in TM_slat_gen.py should be eliminated once everything else is done.
